services:
  frontend-user:
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
    container_name: frontend-user
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
